" ============================================================================
" .vimrc of gayanw 
" ============================================================================

call plug#begin('~/.vim/plugged')

" Plugins
Plug 'tpope/vim-fugitive'

" NERD tree will be loaded on the first invocation of NERDTreeToggle command
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }

Plug 'junegunn/seoul256.vim'

call plug#end()

" Unified color scheme (default: dark)
colo seoul256
