#!/bin/bash

cd $(dirname $BASH_SOURCE)
BASE=$(pwd)

sudo apt-get install openbox
sudo apt-get install numix-gtk-theme

# rc.xml
mkdir -p ~/.config/openbox
mv -v ~/.config/openbox/rc.xml ~/.config/openbox/rc.xml.old 2> /dev/null
ln -sf $BASE/rc.xml ~/.config/openbox/rc.xml

# scrot
mkdir -p ~/Pictures/scrot

# reload configuration
openbox --reconfigure
